---
- name: Converge
  hosts: all
  become: true
  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'
  roles: 
    - role: ned300889.apache
  tasks:
    - name: "Include php-fpm"
      include_role:
        name: "php-fpm"

